# Generated by Django 4.1.7 on 2023-03-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcard', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='static/images/post_pics'),
        ),
    ]
