# Generated by Django 4.1.7 on 2023-04-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvcard', '0006_testimonials_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
